import { Manrope } from "next/font/google";
import { Toaster } from "@/components/ui/sonner"
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
const inter = Manrope({ subsets: ["latin"],weight:["400"] });

export const metadata = {
  title: "Elite Expense",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={inter.className}>
        <Toaster/>
        {children}
        </body>
    </html>
    </ClerkProvider>
  );
}
